# Generated by Django 4.0.1 on 2022-01-07 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(max_length=10, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.CharField(max_length=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
            ],
        ),
    ]
