# Generated by Django 4.0.1 on 2022-01-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
