# Generated by Django 4.0.1 on 2022-01-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rz_invoice_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rz_payment_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
